# Workflow para fazer deploy de conteúdo estático para o GitHub Pages
name: Deploy static content to Pages

on:
  # Roda quando um push é feito para o branch principal
  push:
    branches: ['main'] # Mude para 'master' se for o seu branch principal

  # Permite que você rode este workflow manualmente pela aba Actions
  workflow_dispatch:

# Define as permissões do GITHUB_TOKEN para permitir o deploy no GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Use uma versão mais recente do Node
      - name: Install dependencies with specific versions
        run: |
          npm cache clean --force
          rm -rf node_modules package-lock.json
          npm install --legacy-peer-deps
          npm install @babel/core@7.28.3 semver@6.3.1 --save-exact --legacy-peer-deps
      - name: Verify semver installation
        run: |
          echo "=== Checking semver module ==="
          ls -la node_modules/semver/
          echo "=== Testing semver require ==="
          node -e "console.log('Semver version:', require('semver').version)"
      - name: Build
        run: npm run build
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Faz o upload da pasta 'build'
          path: './build'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4